### ISSUE TITLE
Following the sample, but cron jobs fail

### ISSUE THREAD

**Issue by RobAltena** [GoogleCloudPlatform/reliable-task-scheduling-compute-engine-sample#15]
After setting up the cron job as in the example with 

    gcloud app deploy --version=1 gae/app.yaml \
       gae/cron.yaml

The jobs fail with the[ following error log](https://gist.github.com/RobAltena/c26ffbedf0049da83e96682dd41499a8).

Please let me know if I can help resolve the issue.

**Comment by jpatokal** [comment]
The sample has been updated to use Cloud Scheduler, so App Engine is no longer needed.
