### ISSUE TITLE
Pricing question

### ISSUE THREAD

**Issue by ArielS1** [GoogleCloudPlatform/reliable-task-scheduling-compute-engine-sample#17]
Let's say i run this project to make a single call to a different webhook every 24 hours.
Will the price be usage of 24 hours? or is it in "sleep mode" and i would only be charged for the minimum run time of 15 mins ones a day?

**Comment by naturalethic** [comment]
It seems to me you're incurring the minimum full time cost which comes to $36/mo which is insanely expensive for something like this.

**Comment by naturalethic** [comment]
Digging further, using a single app engine and low volume pub sub is free.

**Comment by jpatokal** [comment]
Cost estimates can be found here:
https://cloud.google.com/solutions/reliable-task-scheduling-compute-engine#cost

If you use a single `f1-micro` VM as suggested, the cost is approximately $0.01/hour or $7.30/month.  Alternatively, if you already have an existing VM, you can just deploy this on the side.
