### ISSUE TITLE
Run cron job from user input to firebase realtime database

### ISSUE THREAD

**Issue by themakerman** [GoogleCloudPlatform/reliable-task-scheduling-compute-engine-sample#20]
Hi,

Is it possible to start a cron job trigger based on time what user entered in one of the nodes of real time database? Can someone please point me to the right direction?

**Comment by jpatokal** [comment]
Cron jobs are intended for tasks you can schedule in advance.   I would suggest looking into Firebase Functions: https://firebase.google.com/docs/functions/
